### ISSUE TITLE
Fix integration with can-map-define

### ISSUE THREAD

**Issue by chasenlehara** [canjs/can-map#147]
When I updated the main CanJS repo with [can-map@4.3.10](https://github.com/canjs/can-map/releases/tag/v4.3.10), this test failed in can-map-define:

<img width="834" alt="Screen Shot 2019-10-04 at 6 26 39 PM" src="https://user-images.githubusercontent.com/10070176/66227178-8f1cdf00-e6d4-11e9-9167-6148206283e7.png">

**Comment by cherifGsoul** [comment]
This is caused by `canReflect.isMapLike([])` the docs says it returns `false` but is returning `true` like in the CodePen

https://codepen.io/cherifGsoul/pen/GRRRKPr?editors=1111

<img width="914" alt="isMapLike___can-reflect___Typed_Data___API_Docs___CanJS" src="https://user-images.githubusercontent.com/109013/66228086-80372c00-e6d6-11e9-80b5-9c48eeee2c61.png">
