### ISSUE TITLE
Error when trying to bind to custom types

### ISSUE THREAD

**Issue by chasenlehara** [canjs/can-map#149]
Sample code from [this CodePen](https://codepen.io/chasenlehara/pen/YzPpvqQ?editors=0010):

```js
class ObjectType extends Object {}

Component.extend({
	tag: "my-buttons",
	view: `{{#each items}}{{/each}}`,
	ViewModel: CanMap.extend({
		define: {
			items: {
				get: function() {
					return new CanList([
						{
							type: new ObjectType({
								label: "hello"
							})
						}
					])
				}
			}
		}
	})
});
```

Expected result: this should render (nothing) without errors

Actual result: this error is thrown: `can-event-queue: Unable to bind change`

I think the above example is the minimum test case for reproducing this issue.

If it helps, this reminds me of https://github.com/canjs/can-list/issues/97

**Comment by bmomberger-bitovi** [comment]
Here's an even more reduced test case ( https://codepen.io/bmomberger-bitovi/pen/QWwdwNg?editors=0010 ):

```
import { CanMap, Reflect } from "//unpkg.com/can@6/everything.mjs";

const foo = new CanMap({
		type: Object.create({
			label: "bye",
		})
});
Reflect.onKeyValue(foo, "change", () => {});
```

If `foo.type` were a plain object (proto === Object.prototype), it would be converted into an observable.  Because it is not a direct Object instance, it it left alone, but when a binding bubbles, like patches for a CanList or change for a CanMap, it's trying to bind to changes on the child (which has not been converted to an observable).

Likely the necessary change is to not to try to bind non-ObservableLike children in a bubble binding.
